# Generated by Django 3.2.6 on 2021-08-12 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_summaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='summaries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), null=True, size=10),
        ),
    ]
