# Generated by Django 3.2.6 on 2021-08-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_summaries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='summaries',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
