# Generated by Django 3.2.6 on 2021-08-13 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210812_1337'),
        ('summaries', '0002_alter_summary_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
