# Generated by Django 3.2.6 on 2021-08-13 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_alter_summary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), null=True, size=5),
        ),
        migrations.AlterField(
            model_name='summary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True), null=True, size=10),
        ),
    ]
