# Generated by Django 3.2.6 on 2021-08-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0005_summary_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='comments',
        ),
    ]
